from flask_restx import reqparse

sysml_element_parser = reqparse.RequestParser()
sysml_element_parser.add_argument('identifier', type=str, required=True, help='Element identifier')
sysml_element_parser.add_argument('title', type=str, required=False, help='Element title')
sysml_element_parser.add_argument('description', type=str, required=False, help='Element description')
sysml_element_parser.add_argument('element_id', type=str, required=False, help='SysML element ID')
sysml_element_parser.add_argument('declared_name', type=str, required=False, help='Declared name')
sysml_element_parser.add_argument('name', type=str, required=False, help='Name')
sysml_element_parser.add_argument('qualified_name', type=str, required=False, help='Qualified name')

sysml_relationship_parser = reqparse.RequestParser()
sysml_relationship_parser.add_argument('identifier', type=str, required=True, help='Relationship identifier')
sysml_relationship_parser.add_argument('title', type=str, required=False, help='Relationship title')
sysml_relationship_parser.add_argument('description', type=str, required=False, help='Relationship description')
sysml_relationship_parser.add_argument('element_id', type=str, required=False, help='SysML element ID')
sysml_relationship_parser.add_argument('declared_name', type=str, required=False, help='Declared name')
sysml_relationship_parser.add_argument('name', type=str, required=False, help='Name')
sysml_relationship_parser.add_argument('source', type=str, action='append', required=False, help='Source elements')
sysml_relationship_parser.add_argument('target', type=str, action='append', required=False, help='Target elements')
sysml_relationship_parser.add_argument('is_implied', type=bool, required=False, help='Is implied')

sysml_package_parser = reqparse.RequestParser()
sysml_package_parser.add_argument('identifier', type=str, required=True, help='Package identifier')
sysml_package_parser.add_argument('title', type=str, required=False, help='Package title')
sysml_package_parser.add_argument('description', type=str, required=False, help='Package description')
sysml_package_parser.add_argument('element_id', type=str, required=False, help='SysML element ID')
sysml_package_parser.add_argument('declared_name', type=str, required=False, help='Declared name')
sysml_package_parser.add_argument('name', type=str, required=False, help='Name')
sysml_package_parser.add_argument('qualified_name', type=str, required=False, help='Qualified name')

sysml_definition_parser = reqparse.RequestParser()
sysml_definition_parser.add_argument('identifier', type=str, required=True, help='Definition identifier')
sysml_definition_parser.add_argument('title', type=str, required=False, help='Definition title')
sysml_definition_parser.add_argument('description', type=str, required=False, help='Definition description')
sysml_definition_parser.add_argument('element_id', type=str, required=False, help='SysML element ID')
sysml_definition_parser.add_argument('declared_name', type=str, required=False, help='Declared name')
sysml_definition_parser.add_argument('name', type=str, required=False, help='Name')
sysml_definition_parser.add_argument('qualified_name', type=str, required=False, help='Qualified name')
sysml_definition_parser.add_argument('is_abstract', type=bool, required=False, help='Is abstract')
sysml_definition_parser.add_argument('is_variation', type=bool, required=False, help='Is variation')

sysml_usage_parser = reqparse.RequestParser()
sysml_usage_parser.add_argument('identifier', type=str, required=True, help='Usage identifier')
sysml_usage_parser.add_argument('title', type=str, required=False, help='Usage title')
sysml_usage_parser.add_argument('description', type=str, required=False, help='Usage description')
sysml_usage_parser.add_argument('element_id', type=str, required=False, help='SysML element ID')
sysml_usage_parser.add_argument('declared_name', type=str, required=False, help='Declared name')
sysml_usage_parser.add_argument('name', type=str, required=False, help='Name')
sysml_usage_parser.add_argument('qualified_name', type=str, required=False, help='Qualified name')
sysml_usage_parser.add_argument('is_reference', type=bool, required=False, help='Is reference')
sysml_usage_parser.add_argument('definition', type=str, action='append', required=False, help='Definition references')

sysml_item_definition_parser = reqparse.RequestParser()
sysml_item_definition_parser.add_argument('identifier', type=str, required=True, help='ItemDefinition identifier')
sysml_item_definition_parser.add_argument('title', type=str, required=False, help='Title')
sysml_item_definition_parser.add_argument('description', type=str, required=False, help='Description')
sysml_item_definition_parser.add_argument('element_id', type=str, required=False, help='SysML element ID')
sysml_item_definition_parser.add_argument('declared_name', type=str, required=False, help='Declared name')
sysml_item_definition_parser.add_argument('name', type=str, required=False, help='Name')
sysml_item_definition_parser.add_argument('owned_occurrence', type=str, action='append', required=False)
sysml_item_definition_parser.add_argument('owned_item', type=str, action='append', required=False)

sysml_item_usage_parser = reqparse.RequestParser()
sysml_item_usage_parser.add_argument('identifier', type=str, required=True, help='ItemUsage identifier')
sysml_item_usage_parser.add_argument('title', type=str, required=False, help='Title')
sysml_item_usage_parser.add_argument('description', type=str, required=False, help='Description')
sysml_item_usage_parser.add_argument('element_id', type=str, required=False, help='SysML element ID')
sysml_item_usage_parser.add_argument('declared_name', type=str, required=False, help='Declared name')
sysml_item_usage_parser.add_argument('name', type=str, required=False, help='Name')
sysml_item_usage_parser.add_argument('occurrence_definition', type=str, required=False)

sysml_part_definition_parser = reqparse.RequestParser()
sysml_part_definition_parser.add_argument('identifier', type=str, required=True, help='PartDefinition identifier')
sysml_part_definition_parser.add_argument('title', type=str, required=False, help='Title')
sysml_part_definition_parser.add_argument('description', type=str, required=False, help='Description')
sysml_part_definition_parser.add_argument('element_id', type=str, required=False, help='SysML element ID')
sysml_part_definition_parser.add_argument('declared_name', type=str, required=False, help='Declared name')
sysml_part_definition_parser.add_argument('name', type=str, required=False, help='Name')
sysml_part_definition_parser.add_argument('is_abstract', type=bool, required=False)
sysml_part_definition_parser.add_argument('owned_part', type=str, action='append', required=False)
sysml_part_definition_parser.add_argument('owned_connection', type=str, action='append', required=False)
sysml_part_definition_parser.add_argument('owned_interface', type=str, action='append', required=False)

sysml_part_usage_parser = reqparse.RequestParser()
sysml_part_usage_parser.add_argument('identifier', type=str, required=True, help='PartUsage identifier')
sysml_part_usage_parser.add_argument('title', type=str, required=False, help='Title')
sysml_part_usage_parser.add_argument('description', type=str, required=False, help='Description')
sysml_part_usage_parser.add_argument('element_id', type=str, required=False, help='SysML element ID')
sysml_part_usage_parser.add_argument('declared_name', type=str, required=False, help='Declared name')
sysml_part_usage_parser.add_argument('name', type=str, required=False, help='Name')
sysml_part_usage_parser.add_argument('is_reference', type=bool, required=False)
sysml_part_usage_parser.add_argument('definition', type=str, action='append', required=False)
sysml_part_usage_parser.add_argument('nested_part', type=str, action='append', required=False)
sysml_part_usage_parser.add_argument('nested_item', type=str, action='append', required=False)
sysml_part_usage_parser.add_argument('nested_connection', type=str, action='append', required=False)
sysml_part_usage_parser.add_argument('nested_interface', type=str, action='append', required=False)

sysml_port_definition_parser = reqparse.RequestParser()
sysml_port_definition_parser.add_argument('identifier', type=str, required=True, help='PortDefinition identifier')
sysml_port_definition_parser.add_argument('title', type=str, required=False, help='Title')
sysml_port_definition_parser.add_argument('description', type=str, required=False, help='Description')
sysml_port_definition_parser.add_argument('element_id', type=str, required=False, help='SysML element ID')
sysml_port_definition_parser.add_argument('declared_name', type=str, required=False, help='Declared name')
sysml_port_definition_parser.add_argument('name', type=str, required=False, help='Name')
sysml_port_definition_parser.add_argument('conjugated_port_definition', type=str, required=False)

sysml_port_usage_parser = reqparse.RequestParser()
sysml_port_usage_parser.add_argument('identifier', type=str, required=True, help='PortUsage identifier')
sysml_port_usage_parser.add_argument('title', type=str, required=False, help='Title')
sysml_port_usage_parser.add_argument('description', type=str, required=False, help='Description')
sysml_port_usage_parser.add_argument('element_id', type=str, required=False, help='SysML element ID')
sysml_port_usage_parser.add_argument('declared_name', type=str, required=False, help='Declared name')
sysml_port_usage_parser.add_argument('name', type=str, required=False, help='Name')
sysml_port_usage_parser.add_argument('is_reference', type=bool, required=False)
sysml_port_usage_parser.add_argument('definition', type=str, action='append', required=False)
sysml_port_usage_parser.add_argument('conjugated_port_definition', type=str, required=False)
sysml_port_usage_parser.add_argument('nested_connection', type=str, action='append', required=False)
sysml_port_usage_parser.add_argument('nested_interface', type=str, action='append', required=False)

sysml_requirement_definition_parser = reqparse.RequestParser()
sysml_requirement_definition_parser.add_argument('identifier', type=str, required=True,
                                                 help='RequirementDefinition identifier')
sysml_requirement_definition_parser.add_argument('title', type=str, required=False)
sysml_requirement_definition_parser.add_argument('description', type=str, required=False)
sysml_requirement_definition_parser.add_argument('element_id', type=str, required=False)
sysml_requirement_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_requirement_definition_parser.add_argument('name', type=str, required=False)
sysml_requirement_definition_parser.add_argument('req_id', type=str, required=False)
sysml_requirement_definition_parser.add_argument('text', type=str, action='append', required=False)
sysml_requirement_definition_parser.add_argument('assumed_constraint', type=str,
                                                 action='append', required=False)
sysml_requirement_definition_parser.add_argument('required_constraint', type=str,
                                                 action='append', required=False)
sysml_requirement_definition_parser.add_argument('framed_concern', type=str,
                                                 action='append', required=False)
sysml_requirement_definition_parser.add_argument('referenced_concern', type=str,
                                                 action='append', required=False)
sysml_requirement_definition_parser.add_argument('owned_concern', type=str,
                                                 action='append', required=False)
sysml_requirement_definition_parser.add_argument('owned_viewpoint', type=str,
                                                 action='append', required=False)
sysml_requirement_definition_parser.add_argument('owned_objective_requirement', type=str,
                                                 required=False)

sysml_requirement_usage_parser = reqparse.RequestParser()
sysml_requirement_usage_parser.add_argument('identifier', type=str, required=True,
                                            help='RequirementUsage identifier')
sysml_requirement_usage_parser.add_argument('title', type=str, required=False)
sysml_requirement_usage_parser.add_argument('description', type=str, required=False)
sysml_requirement_usage_parser.add_argument('element_id', type=str, required=False)
sysml_requirement_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_requirement_usage_parser.add_argument('name', type=str, required=False)
sysml_requirement_usage_parser.add_argument('req_id', type=str, required=False)
sysml_requirement_usage_parser.add_argument('text', type=str, action='append', required=False)
sysml_requirement_usage_parser.add_argument('assumed_constraint', type=str,
                                            action='append', required=False)
sysml_requirement_usage_parser.add_argument('required_constraint', type=str,
                                            action='append', required=False)
sysml_requirement_usage_parser.add_argument('framed_concern', type=str,
                                            action='append', required=False)
sysml_requirement_usage_parser.add_argument('referenced_concern', type=str,
                                            action='append', required=False)
sysml_requirement_usage_parser.add_argument('satisfied_requirement', type=str,
                                            action='append', required=False)
sysml_requirement_usage_parser.add_argument('satisfied_viewpoint', type=str,
                                            action='append', required=False)
sysml_requirement_usage_parser.add_argument('verified_requirement', type=str,
                                            action='append', required=False)

sysml_concern_definition_parser = reqparse.RequestParser()
sysml_concern_definition_parser.add_argument('identifier', type=str, required=True,
                                             help='ConcernDefinition identifier')
sysml_concern_definition_parser.add_argument('title', type=str, required=False)
sysml_concern_definition_parser.add_argument('description', type=str, required=False)
sysml_concern_definition_parser.add_argument('element_id', type=str, required=False)
sysml_concern_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_concern_definition_parser.add_argument('name', type=str, required=False)
sysml_concern_definition_parser.add_argument('req_id', type=str, required=False)
sysml_concern_definition_parser.add_argument('text', type=str, action='append', required=False)

sysml_concern_usage_parser = reqparse.RequestParser()
sysml_concern_usage_parser.add_argument('identifier', type=str, required=True,
                                        help='ConcernUsage identifier')
sysml_concern_usage_parser.add_argument('title', type=str, required=False)
sysml_concern_usage_parser.add_argument('description', type=str, required=False)
sysml_concern_usage_parser.add_argument('element_id', type=str, required=False)
sysml_concern_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_concern_usage_parser.add_argument('name', type=str, required=False)
sysml_concern_usage_parser.add_argument('req_id', type=str, required=False)
sysml_concern_usage_parser.add_argument('text', type=str, action='append', required=False)

sysml_action_definition_parser = reqparse.RequestParser()
sysml_action_definition_parser.add_argument('identifier', type=str, required=True,
                                            help='ActionDefinition identifier')
sysml_action_definition_parser.add_argument('title', type=str, required=False)
sysml_action_definition_parser.add_argument('description', type=str, required=False)
sysml_action_definition_parser.add_argument('element_id', type=str, required=False)
sysml_action_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_action_definition_parser.add_argument('name', type=str, required=False)
sysml_action_definition_parser.add_argument('action', type=str, action='append', required=False)
sysml_action_definition_parser.add_argument('behavior', type=str, action='append', required=False)
sysml_action_definition_parser.add_argument('step', type=str, action='append', required=False)
sysml_action_definition_parser.add_argument('parameter', type=str, action='append', required=False)
sysml_action_definition_parser.add_argument('owned_state', type=str, action='append', required=False)
sysml_action_definition_parser.add_argument('owned_transition', type=str,
                                            action='append', required=False)

sysml_action_usage_parser = reqparse.RequestParser()
sysml_action_usage_parser.add_argument('identifier', type=str, required=True,
                                       help='ActionUsage identifier')
sysml_action_usage_parser.add_argument('title', type=str, required=False)
sysml_action_usage_parser.add_argument('description', type=str, required=False)
sysml_action_usage_parser.add_argument('element_id', type=str, required=False)
sysml_action_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_action_usage_parser.add_argument('name', type=str, required=False)
sysml_action_usage_parser.add_argument('action_definition', type=str, required=False)
sysml_action_usage_parser.add_argument('behavior', type=str, action='append', required=False)
sysml_action_usage_parser.add_argument('nested_state', type=str, action='append', required=False)
sysml_action_usage_parser.add_argument('nested_transition', type=str,
                                       action='append', required=False)

sysml_state_definition_parser = reqparse.RequestParser()
sysml_state_definition_parser.add_argument('identifier', type=str, required=True,
                                           help='StateDefinition identifier')
sysml_state_definition_parser.add_argument('title', type=str, required=False)
sysml_state_definition_parser.add_argument('description', type=str, required=False)
sysml_state_definition_parser.add_argument('element_id', type=str, required=False)
sysml_state_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_state_definition_parser.add_argument('name', type=str, required=False)
sysml_state_definition_parser.add_argument('state', type=str, action='append', required=False)
sysml_state_definition_parser.add_argument('entry_action', type=str, required=False)
sysml_state_definition_parser.add_argument('do_action', type=str, required=False)
sysml_state_definition_parser.add_argument('exit_action', type=str, required=False)

sysml_state_usage_parser = reqparse.RequestParser()
sysml_state_usage_parser.add_argument('identifier', type=str, required=True,
                                      help='StateUsage identifier')
sysml_state_usage_parser.add_argument('title', type=str, required=False)
sysml_state_usage_parser.add_argument('description', type=str, required=False)
sysml_state_usage_parser.add_argument('element_id', type=str, required=False)
sysml_state_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_state_usage_parser.add_argument('name', type=str, required=False)
sysml_state_usage_parser.add_argument('state_definition', type=str, required=False)

sysml_constraint_definition_parser = reqparse.RequestParser()
sysml_constraint_definition_parser.add_argument('identifier', type=str, required=True,
                                                help='ConstraintDefinition identifier')
sysml_constraint_definition_parser.add_argument('title', type=str, required=False)
sysml_constraint_definition_parser.add_argument('description', type=str, required=False)
sysml_constraint_definition_parser.add_argument('element_id', type=str, required=False)
sysml_constraint_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_constraint_definition_parser.add_argument('name', type=str, required=False)
sysml_constraint_definition_parser.add_argument('is_negated', type=bool, required=False)

sysml_constraint_usage_parser = reqparse.RequestParser()
sysml_constraint_usage_parser.add_argument('identifier', type=str, required=True,
                                           help='ConstraintUsage identifier')
sysml_constraint_usage_parser.add_argument('title', type=str, required=False)
sysml_constraint_usage_parser.add_argument('description', type=str, required=False)
sysml_constraint_usage_parser.add_argument('element_id', type=str, required=False)
sysml_constraint_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_constraint_usage_parser.add_argument('name', type=str, required=False)
sysml_constraint_usage_parser.add_argument('is_negated', type=bool, required=False)
sysml_constraint_usage_parser.add_argument('constraint_definition', type=str, required=False)

sysml_view_definition_parser = reqparse.RequestParser()
sysml_view_definition_parser.add_argument('identifier', type=str, required=True,
                                          help='ViewDefinition identifier')
sysml_view_definition_parser.add_argument('title', type=str, required=False)
sysml_view_definition_parser.add_argument('description', type=str, required=False)
sysml_view_definition_parser.add_argument('element_id', type=str, required=False)
sysml_view_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_view_definition_parser.add_argument('name', type=str, required=False)
sysml_view_definition_parser.add_argument('is_abstract', type=bool, required=False)
sysml_view_definition_parser.add_argument('view_condition', type=str, required=False)
sysml_view_definition_parser.add_argument('view_rendering', type=str, required=False)
sysml_view_definition_parser.add_argument('exposed_element', type=str, action='append', required=False)

sysml_view_usage_parser = reqparse.RequestParser()
sysml_view_usage_parser.add_argument('identifier', type=str, required=True,
                                     help='ViewUsage identifier')
sysml_view_usage_parser.add_argument('title', type=str, required=False)
sysml_view_usage_parser.add_argument('description', type=str, required=False)
sysml_view_usage_parser.add_argument('element_id', type=str, required=False)
sysml_view_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_view_usage_parser.add_argument('name', type=str, required=False)
sysml_view_usage_parser.add_argument('is_reference', type=bool, required=False)
sysml_view_usage_parser.add_argument('definition', type=str, action='append', required=False)
sysml_view_usage_parser.add_argument('view_definition', type=str, required=False)
sysml_view_usage_parser.add_argument('view_condition', type=str, required=False)
sysml_view_usage_parser.add_argument('view_rendering', type=str, required=False)
sysml_view_usage_parser.add_argument('exposed_element', type=str, action='append', required=False)
sysml_view_usage_parser.add_argument('satisfied_viewpoint', type=str, action='append', required=False)

sysml_viewpoint_definition_parser = reqparse.RequestParser()
sysml_viewpoint_definition_parser.add_argument('identifier', type=str, required=True,
                                               help='ViewpointDefinition identifier')
sysml_viewpoint_definition_parser.add_argument('title', type=str, required=False)
sysml_viewpoint_definition_parser.add_argument('description', type=str, required=False)
sysml_viewpoint_definition_parser.add_argument('element_id', type=str, required=False)
sysml_viewpoint_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_viewpoint_definition_parser.add_argument('name', type=str, required=False)
sysml_viewpoint_definition_parser.add_argument('req_id', type=str, required=False)
sysml_viewpoint_definition_parser.add_argument('text', type=str, action='append', required=False)
sysml_viewpoint_definition_parser.add_argument('viewpoint_stakeholder', type=str,
                                               action='append', required=False)
sysml_viewpoint_definition_parser.add_argument('satisfied_viewpoint', type=str,
                                               action='append', required=False)

sysml_viewpoint_usage_parser = reqparse.RequestParser()
sysml_viewpoint_usage_parser.add_argument('identifier', type=str, required=True,
                                          help='ViewpointUsage identifier')
sysml_viewpoint_usage_parser.add_argument('title', type=str, required=False)
sysml_viewpoint_usage_parser.add_argument('description', type=str, required=False)
sysml_viewpoint_usage_parser.add_argument('element_id', type=str, required=False)
sysml_viewpoint_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_viewpoint_usage_parser.add_argument('name', type=str, required=False)
sysml_viewpoint_usage_parser.add_argument('req_id', type=str, required=False)
sysml_viewpoint_usage_parser.add_argument('text', type=str, action='append', required=False)
sysml_viewpoint_usage_parser.add_argument('satisfied_requirement', type=str,
                                          action='append', required=False)
sysml_viewpoint_usage_parser.add_argument('satisfied_viewpoint', type=str,
                                          action='append', required=False)
sysml_viewpoint_usage_parser.add_argument('viewpoint_definition', type=str, required=False)
sysml_viewpoint_usage_parser.add_argument('viewpoint_stakeholder', type=str,
                                          action='append', required=False)

# --- Phase 8 parsers ---

sysml_feature_parser = reqparse.RequestParser()
sysml_feature_parser.add_argument('identifier', type=str, required=True)
sysml_feature_parser.add_argument('title', type=str, required=False)
sysml_feature_parser.add_argument('description', type=str, required=False)
sysml_feature_parser.add_argument('element_id', type=str, required=False)
sysml_feature_parser.add_argument('declared_name', type=str, required=False)
sysml_feature_parser.add_argument('name', type=str, required=False)
sysml_feature_parser.add_argument('is_composite', type=bool, required=False)
sysml_feature_parser.add_argument('is_derived', type=bool, required=False)
sysml_feature_parser.add_argument('is_end', type=bool, required=False)
sysml_feature_parser.add_argument('is_ordered', type=bool, required=False)
sysml_feature_parser.add_argument('is_portion', type=bool, required=False)
sysml_feature_parser.add_argument('is_read_only', type=bool, required=False)
sysml_feature_parser.add_argument('is_unique', type=bool, required=False)
sysml_feature_parser.add_argument('direction', type=str, required=False)

sysml_classifier_parser = reqparse.RequestParser()
sysml_classifier_parser.add_argument('identifier', type=str, required=True)
sysml_classifier_parser.add_argument('title', type=str, required=False)
sysml_classifier_parser.add_argument('description', type=str, required=False)
sysml_classifier_parser.add_argument('element_id', type=str, required=False)
sysml_classifier_parser.add_argument('declared_name', type=str, required=False)
sysml_classifier_parser.add_argument('name', type=str, required=False)
sysml_classifier_parser.add_argument('is_variation', type=bool, required=False)

sysml_occurrence_definition_parser = reqparse.RequestParser()
sysml_occurrence_definition_parser.add_argument('identifier', type=str, required=True)
sysml_occurrence_definition_parser.add_argument('title', type=str, required=False)
sysml_occurrence_definition_parser.add_argument('description', type=str, required=False)
sysml_occurrence_definition_parser.add_argument('element_id', type=str, required=False)
sysml_occurrence_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_occurrence_definition_parser.add_argument('name', type=str, required=False)
sysml_occurrence_definition_parser.add_argument('is_sufficient', type=bool, required=False)

sysml_occurrence_usage_parser = reqparse.RequestParser()
sysml_occurrence_usage_parser.add_argument('identifier', type=str, required=True)
sysml_occurrence_usage_parser.add_argument('title', type=str, required=False)
sysml_occurrence_usage_parser.add_argument('description', type=str, required=False)
sysml_occurrence_usage_parser.add_argument('element_id', type=str, required=False)
sysml_occurrence_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_occurrence_usage_parser.add_argument('name', type=str, required=False)
sysml_occurrence_usage_parser.add_argument('is_reference', type=bool, required=False)
sysml_occurrence_usage_parser.add_argument('may_time_vary', type=bool, required=False)
sysml_occurrence_usage_parser.add_argument('portion_kind', type=str, required=False)
sysml_occurrence_usage_parser.add_argument('definition', type=str, action='append', required=False)

sysml_class_parser = reqparse.RequestParser()
sysml_class_parser.add_argument('identifier', type=str, required=True)
sysml_class_parser.add_argument('title', type=str, required=False)
sysml_class_parser.add_argument('description', type=str, required=False)
sysml_class_parser.add_argument('element_id', type=str, required=False)
sysml_class_parser.add_argument('declared_name', type=str, required=False)
sysml_class_parser.add_argument('name', type=str, required=False)

sysml_structure_parser = reqparse.RequestParser()
sysml_structure_parser.add_argument('identifier', type=str, required=True)
sysml_structure_parser.add_argument('title', type=str, required=False)
sysml_structure_parser.add_argument('description', type=str, required=False)
sysml_structure_parser.add_argument('element_id', type=str, required=False)
sysml_structure_parser.add_argument('declared_name', type=str, required=False)
sysml_structure_parser.add_argument('name', type=str, required=False)

sysml_data_type_parser = reqparse.RequestParser()
sysml_data_type_parser.add_argument('identifier', type=str, required=True)
sysml_data_type_parser.add_argument('title', type=str, required=False)
sysml_data_type_parser.add_argument('description', type=str, required=False)
sysml_data_type_parser.add_argument('element_id', type=str, required=False)
sysml_data_type_parser.add_argument('declared_name', type=str, required=False)
sysml_data_type_parser.add_argument('name', type=str, required=False)

sysml_behavior_parser = reqparse.RequestParser()
sysml_behavior_parser.add_argument('identifier', type=str, required=True)
sysml_behavior_parser.add_argument('title', type=str, required=False)
sysml_behavior_parser.add_argument('description', type=str, required=False)
sysml_behavior_parser.add_argument('element_id', type=str, required=False)
sysml_behavior_parser.add_argument('declared_name', type=str, required=False)
sysml_behavior_parser.add_argument('name', type=str, required=False)

sysml_function_parser = reqparse.RequestParser()
sysml_function_parser.add_argument('identifier', type=str, required=True)
sysml_function_parser.add_argument('title', type=str, required=False)
sysml_function_parser.add_argument('description', type=str, required=False)
sysml_function_parser.add_argument('element_id', type=str, required=False)
sysml_function_parser.add_argument('declared_name', type=str, required=False)
sysml_function_parser.add_argument('name', type=str, required=False)

sysml_predicate_parser = reqparse.RequestParser()
sysml_predicate_parser.add_argument('identifier', type=str, required=True)
sysml_predicate_parser.add_argument('title', type=str, required=False)
sysml_predicate_parser.add_argument('description', type=str, required=False)
sysml_predicate_parser.add_argument('element_id', type=str, required=False)
sysml_predicate_parser.add_argument('declared_name', type=str, required=False)
sysml_predicate_parser.add_argument('name', type=str, required=False)

sysml_library_package_parser = reqparse.RequestParser()
sysml_library_package_parser.add_argument('identifier', type=str, required=True)
sysml_library_package_parser.add_argument('title', type=str, required=False)
sysml_library_package_parser.add_argument('description', type=str, required=False)
sysml_library_package_parser.add_argument('element_id', type=str, required=False)
sysml_library_package_parser.add_argument('declared_name', type=str, required=False)
sysml_library_package_parser.add_argument('name', type=str, required=False)

sysml_attribute_definition_parser = reqparse.RequestParser()
sysml_attribute_definition_parser.add_argument('identifier', type=str, required=True)
sysml_attribute_definition_parser.add_argument('title', type=str, required=False)
sysml_attribute_definition_parser.add_argument('description', type=str, required=False)
sysml_attribute_definition_parser.add_argument('element_id', type=str, required=False)
sysml_attribute_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_attribute_definition_parser.add_argument('name', type=str, required=False)

sysml_attribute_usage_parser = reqparse.RequestParser()
sysml_attribute_usage_parser.add_argument('identifier', type=str, required=True)
sysml_attribute_usage_parser.add_argument('title', type=str, required=False)
sysml_attribute_usage_parser.add_argument('description', type=str, required=False)
sysml_attribute_usage_parser.add_argument('element_id', type=str, required=False)
sysml_attribute_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_attribute_usage_parser.add_argument('name', type=str, required=False)

sysml_enumeration_definition_parser = reqparse.RequestParser()
sysml_enumeration_definition_parser.add_argument('identifier', type=str, required=True)
sysml_enumeration_definition_parser.add_argument('title', type=str, required=False)
sysml_enumeration_definition_parser.add_argument('description', type=str, required=False)
sysml_enumeration_definition_parser.add_argument('element_id', type=str, required=False)
sysml_enumeration_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_enumeration_definition_parser.add_argument('name', type=str, required=False)

sysml_enumeration_usage_parser = reqparse.RequestParser()
sysml_enumeration_usage_parser.add_argument('identifier', type=str, required=True)
sysml_enumeration_usage_parser.add_argument('title', type=str, required=False)
sysml_enumeration_usage_parser.add_argument('description', type=str, required=False)
sysml_enumeration_usage_parser.add_argument('element_id', type=str, required=False)
sysml_enumeration_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_enumeration_usage_parser.add_argument('name', type=str, required=False)

sysml_calculation_definition_parser = reqparse.RequestParser()
sysml_calculation_definition_parser.add_argument('identifier', type=str, required=True)
sysml_calculation_definition_parser.add_argument('title', type=str, required=False)
sysml_calculation_definition_parser.add_argument('description', type=str, required=False)
sysml_calculation_definition_parser.add_argument('element_id', type=str, required=False)
sysml_calculation_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_calculation_definition_parser.add_argument('name', type=str, required=False)

sysml_calculation_usage_parser = reqparse.RequestParser()
sysml_calculation_usage_parser.add_argument('identifier', type=str, required=True)
sysml_calculation_usage_parser.add_argument('title', type=str, required=False)
sysml_calculation_usage_parser.add_argument('description', type=str, required=False)
sysml_calculation_usage_parser.add_argument('element_id', type=str, required=False)
sysml_calculation_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_calculation_usage_parser.add_argument('name', type=str, required=False)

sysml_case_definition_parser = reqparse.RequestParser()
sysml_case_definition_parser.add_argument('identifier', type=str, required=True)
sysml_case_definition_parser.add_argument('title', type=str, required=False)
sysml_case_definition_parser.add_argument('description', type=str, required=False)
sysml_case_definition_parser.add_argument('element_id', type=str, required=False)
sysml_case_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_case_definition_parser.add_argument('name', type=str, required=False)

sysml_case_usage_parser = reqparse.RequestParser()
sysml_case_usage_parser.add_argument('identifier', type=str, required=True)
sysml_case_usage_parser.add_argument('title', type=str, required=False)
sysml_case_usage_parser.add_argument('description', type=str, required=False)
sysml_case_usage_parser.add_argument('element_id', type=str, required=False)
sysml_case_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_case_usage_parser.add_argument('name', type=str, required=False)

sysml_use_case_definition_parser = reqparse.RequestParser()
sysml_use_case_definition_parser.add_argument('identifier', type=str, required=True)
sysml_use_case_definition_parser.add_argument('title', type=str, required=False)
sysml_use_case_definition_parser.add_argument('description', type=str, required=False)
sysml_use_case_definition_parser.add_argument('element_id', type=str, required=False)
sysml_use_case_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_use_case_definition_parser.add_argument('name', type=str, required=False)

sysml_use_case_usage_parser = reqparse.RequestParser()
sysml_use_case_usage_parser.add_argument('identifier', type=str, required=True)
sysml_use_case_usage_parser.add_argument('title', type=str, required=False)
sysml_use_case_usage_parser.add_argument('description', type=str, required=False)
sysml_use_case_usage_parser.add_argument('element_id', type=str, required=False)
sysml_use_case_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_use_case_usage_parser.add_argument('name', type=str, required=False)

sysml_analysis_case_definition_parser = reqparse.RequestParser()
sysml_analysis_case_definition_parser.add_argument('identifier', type=str, required=True)
sysml_analysis_case_definition_parser.add_argument('title', type=str, required=False)
sysml_analysis_case_definition_parser.add_argument('description', type=str, required=False)
sysml_analysis_case_definition_parser.add_argument('element_id', type=str, required=False)
sysml_analysis_case_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_analysis_case_definition_parser.add_argument('name', type=str, required=False)

sysml_analysis_case_usage_parser = reqparse.RequestParser()
sysml_analysis_case_usage_parser.add_argument('identifier', type=str, required=True)
sysml_analysis_case_usage_parser.add_argument('title', type=str, required=False)
sysml_analysis_case_usage_parser.add_argument('description', type=str, required=False)
sysml_analysis_case_usage_parser.add_argument('element_id', type=str, required=False)
sysml_analysis_case_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_analysis_case_usage_parser.add_argument('name', type=str, required=False)

sysml_verification_case_definition_parser = reqparse.RequestParser()
sysml_verification_case_definition_parser.add_argument('identifier', type=str, required=True)
sysml_verification_case_definition_parser.add_argument('title', type=str, required=False)
sysml_verification_case_definition_parser.add_argument('description', type=str, required=False)
sysml_verification_case_definition_parser.add_argument('element_id', type=str, required=False)
sysml_verification_case_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_verification_case_definition_parser.add_argument('name', type=str, required=False)

sysml_verification_case_usage_parser = reqparse.RequestParser()
sysml_verification_case_usage_parser.add_argument('identifier', type=str, required=True)
sysml_verification_case_usage_parser.add_argument('title', type=str, required=False)
sysml_verification_case_usage_parser.add_argument('description', type=str, required=False)
sysml_verification_case_usage_parser.add_argument('element_id', type=str, required=False)
sysml_verification_case_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_verification_case_usage_parser.add_argument('name', type=str, required=False)

sysml_connection_definition_parser = reqparse.RequestParser()
sysml_connection_definition_parser.add_argument('identifier', type=str, required=True)
sysml_connection_definition_parser.add_argument('title', type=str, required=False)
sysml_connection_definition_parser.add_argument('description', type=str, required=False)
sysml_connection_definition_parser.add_argument('element_id', type=str, required=False)
sysml_connection_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_connection_definition_parser.add_argument('name', type=str, required=False)

sysml_connection_usage_parser = reqparse.RequestParser()
sysml_connection_usage_parser.add_argument('identifier', type=str, required=True)
sysml_connection_usage_parser.add_argument('title', type=str, required=False)
sysml_connection_usage_parser.add_argument('description', type=str, required=False)
sysml_connection_usage_parser.add_argument('element_id', type=str, required=False)
sysml_connection_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_connection_usage_parser.add_argument('name', type=str, required=False)

sysml_flow_definition_parser = reqparse.RequestParser()
sysml_flow_definition_parser.add_argument('identifier', type=str, required=True)
sysml_flow_definition_parser.add_argument('title', type=str, required=False)
sysml_flow_definition_parser.add_argument('description', type=str, required=False)
sysml_flow_definition_parser.add_argument('element_id', type=str, required=False)
sysml_flow_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_flow_definition_parser.add_argument('name', type=str, required=False)

sysml_flow_usage_parser = reqparse.RequestParser()
sysml_flow_usage_parser.add_argument('identifier', type=str, required=True)
sysml_flow_usage_parser.add_argument('title', type=str, required=False)
sysml_flow_usage_parser.add_argument('description', type=str, required=False)
sysml_flow_usage_parser.add_argument('element_id', type=str, required=False)
sysml_flow_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_flow_usage_parser.add_argument('name', type=str, required=False)

sysml_interface_definition_parser = reqparse.RequestParser()
sysml_interface_definition_parser.add_argument('identifier', type=str, required=True)
sysml_interface_definition_parser.add_argument('title', type=str, required=False)
sysml_interface_definition_parser.add_argument('description', type=str, required=False)
sysml_interface_definition_parser.add_argument('element_id', type=str, required=False)
sysml_interface_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_interface_definition_parser.add_argument('name', type=str, required=False)

sysml_interface_usage_parser = reqparse.RequestParser()
sysml_interface_usage_parser.add_argument('identifier', type=str, required=True)
sysml_interface_usage_parser.add_argument('title', type=str, required=False)
sysml_interface_usage_parser.add_argument('description', type=str, required=False)
sysml_interface_usage_parser.add_argument('element_id', type=str, required=False)
sysml_interface_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_interface_usage_parser.add_argument('name', type=str, required=False)

sysml_allocation_definition_parser = reqparse.RequestParser()
sysml_allocation_definition_parser.add_argument('identifier', type=str, required=True)
sysml_allocation_definition_parser.add_argument('title', type=str, required=False)
sysml_allocation_definition_parser.add_argument('description', type=str, required=False)
sysml_allocation_definition_parser.add_argument('element_id', type=str, required=False)
sysml_allocation_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_allocation_definition_parser.add_argument('name', type=str, required=False)

sysml_allocation_usage_parser = reqparse.RequestParser()
sysml_allocation_usage_parser.add_argument('identifier', type=str, required=True)
sysml_allocation_usage_parser.add_argument('title', type=str, required=False)
sysml_allocation_usage_parser.add_argument('description', type=str, required=False)
sysml_allocation_usage_parser.add_argument('element_id', type=str, required=False)
sysml_allocation_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_allocation_usage_parser.add_argument('name', type=str, required=False)

sysml_rendering_definition_parser = reqparse.RequestParser()
sysml_rendering_definition_parser.add_argument('identifier', type=str, required=True)
sysml_rendering_definition_parser.add_argument('title', type=str, required=False)
sysml_rendering_definition_parser.add_argument('description', type=str, required=False)
sysml_rendering_definition_parser.add_argument('element_id', type=str, required=False)
sysml_rendering_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_rendering_definition_parser.add_argument('name', type=str, required=False)

sysml_rendering_usage_parser = reqparse.RequestParser()
sysml_rendering_usage_parser.add_argument('identifier', type=str, required=True)
sysml_rendering_usage_parser.add_argument('title', type=str, required=False)
sysml_rendering_usage_parser.add_argument('description', type=str, required=False)
sysml_rendering_usage_parser.add_argument('element_id', type=str, required=False)
sysml_rendering_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_rendering_usage_parser.add_argument('name', type=str, required=False)

sysml_reference_usage_parser = reqparse.RequestParser()
sysml_reference_usage_parser.add_argument('identifier', type=str, required=True)
sysml_reference_usage_parser.add_argument('title', type=str, required=False)
sysml_reference_usage_parser.add_argument('description', type=str, required=False)
sysml_reference_usage_parser.add_argument('element_id', type=str, required=False)
sysml_reference_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_reference_usage_parser.add_argument('name', type=str, required=False)

sysml_conjugated_port_definition_parser = reqparse.RequestParser()
sysml_conjugated_port_definition_parser.add_argument('identifier', type=str, required=True)
sysml_conjugated_port_definition_parser.add_argument('title', type=str, required=False)
sysml_conjugated_port_definition_parser.add_argument('description', type=str, required=False)
sysml_conjugated_port_definition_parser.add_argument('element_id', type=str, required=False)
sysml_conjugated_port_definition_parser.add_argument('declared_name', type=str, required=False)
sysml_conjugated_port_definition_parser.add_argument('name', type=str, required=False)

sysml_connector_as_usage_parser = reqparse.RequestParser()
sysml_connector_as_usage_parser.add_argument('identifier', type=str, required=True)
sysml_connector_as_usage_parser.add_argument('title', type=str, required=False)
sysml_connector_as_usage_parser.add_argument('description', type=str, required=False)
sysml_connector_as_usage_parser.add_argument('element_id', type=str, required=False)
sysml_connector_as_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_connector_as_usage_parser.add_argument('name', type=str, required=False)

sysml_succession_as_usage_parser = reqparse.RequestParser()
sysml_succession_as_usage_parser.add_argument('identifier', type=str, required=True)
sysml_succession_as_usage_parser.add_argument('title', type=str, required=False)
sysml_succession_as_usage_parser.add_argument('description', type=str, required=False)
sysml_succession_as_usage_parser.add_argument('element_id', type=str, required=False)
sysml_succession_as_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_succession_as_usage_parser.add_argument('name', type=str, required=False)

sysml_binding_connector_as_usage_parser = reqparse.RequestParser()
sysml_binding_connector_as_usage_parser.add_argument('identifier', type=str, required=True)
sysml_binding_connector_as_usage_parser.add_argument('title', type=str, required=False)
sysml_binding_connector_as_usage_parser.add_argument('description', type=str, required=False)
sysml_binding_connector_as_usage_parser.add_argument('element_id', type=str, required=False)
sysml_binding_connector_as_usage_parser.add_argument('declared_name', type=str, required=False)
sysml_binding_connector_as_usage_parser.add_argument('name', type=str, required=False)
sysml_viewpoint_usage_parser.add_argument('viewpoint_definition', type=str, required=False)
sysml_viewpoint_usage_parser.add_argument('viewpoint_stakeholder', type=str,
                                          action='append', required=False)
